import { Property, Realtor, Inquiry, User } from './types';

export const INITIAL_REALTORS: Realtor[] = [
  {
    id: 'david',
    name: 'David Vandervelde',
    title: 'Elite Architectural Realtor',
    profileImage: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&h=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    city: 'Vancouver',
    phone: '+1 (604) 555-0192',
    whatsapp: '+16045550192',
    bio: 'Specializing in contemporary West Coast minimalist architecture and concrete estate dwellings. Over fifteen years of curate representation in premium luxury segments.',
    experience: 15,
    languages: ['English', 'German', 'Dutch'],
    specializations: ['Penthouses', 'Architectural Glass Homes', 'Waterfront Estates'],
    template: 'Minimal',
    customDomain: 'davidvandervelde.com',
    agencyName: 'Apex Luxury Realty',
    licenseNumber: 'BC-992384-L',
    email: 'david@apexluxury.com'
  },
  {
    id: 'sarah',
    name: 'Sarah Sterling',
    title: 'Managing Director, Sterling Group',
    profileImage: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&h=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
    city: 'Toronto',
    phone: '+1 (416) 555-4819',
    whatsapp: '+14165554819',
    bio: 'Dedicated to presenting high-end modern penthouses and custom-tailored residential buildings. Helping discerning clients find their private structural masterpieces.',
    experience: 12,
    languages: ['English', 'French', 'Mandarin'],
    specializations: ['Luxury Lofts', 'Urban Penthouses', 'Modern Townhomes'],
    template: 'Luxury',
    customDomain: 'sterlingluxury.ca',
    agencyName: 'Sterling Group Estates',
    licenseNumber: 'ON-481920-A',
    email: 'sarah@sterlingluxury.ca'
  },
  {
    id: 'julian',
    name: 'Julian Rose',
    title: 'Principal Designer & Broker',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&h=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
    city: 'Montreal',
    phone: '+1 (514) 555-8327',
    whatsapp: '+15145558327',
    bio: 'Bridging architectural design literacy with real estate advisory. Focusing on mid-century modernist restorations and high-comfort solar passive villas.',
    experience: 8,
    languages: ['English', 'French', 'Spanish'],
    specializations: ['Modernist Villas', 'Solar Passive Estates', 'Historical Restorations'],
    template: 'Modern',
    customDomain: 'julianroseresidences.com',
    agencyName: 'Rose & Partners Advisory',
    licenseNumber: 'QC-832711-B',
    email: 'julian@roseproperties.com'
  }
];

export const INITIAL_PROPERTIES: Property[] = [
  {
    property_id: 2001,
    owner_id: 'david',
    title: 'The West Coast Horizon Residence',
    description: 'This masterfully designed architectural estate offers dramatic floor-to-ceiling glass walls, suspended steel rafters, and warm local red cedar finishes. Perched gracefully on a cliffside, it integrates the natural coastal ecology with state-of-the-art home automation and high-efficiency geothermal underfloor heating. Complete with a private forest trail and direct cove access, this residence represents the absolute pinnacle of Pacific Northwest modern design.',
    price: 6850000,
    bedrooms: 4,
    bathrooms: 5,
    area: 5800,
    propertyType: 'House',
    amenities: ['Swimming Pool', 'Gym', 'Garden', 'Balcony', 'Terrace', 'Security', 'CCTV', 'Air Conditioning', 'Central Heating', 'High-Speed Internet', 'Smart Home', 'EV Charging', 'Sea View'],
    address: '3120 Marine Drive',
    city: 'Vancouver',
    province: 'British Columbia',
    postalCode: 'V7V 1N8',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'Available',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Buy',
    currency: 'CAD',
    shortDescription: 'A stunning architectural waterfront house nestled in West Vancouver cliffs.',
    country: 'Canada',
    areaCommunity: 'West Vancouver Waterfront',
    googleMapLocation: 'https://maps.google.com/?q=49.3364,-123.2384',
    nearbyLandmarksText: 'Lighthouse Park, Whytecliff Park, West Bay Elementary',
    kitchens: 2,
    livingRooms: 2,
    diningRooms: 1,
    parkingSpaces: 3,
    floorNumber: 1,
    totalFloors: 3,
    propertySize: 5800,
    lotSize: 12000,
    yearBuilt: 2024,
    propertyCondition: 'New',
    furnishedStatus: 'Semi-Furnished',
    estMonthlyRentalIncome: 24000,
    estAnnualRentalIncome: 288000,
    grossRentalYield: 4.2,
    estRoi: 8.5,
    propertyTax: 18500,
    hoaMaintenanceFee: 0,
    estMonthlyMaintenance: 1200,
    coverImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    videoTour: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    virtualTour360: 'https://my.matterport.com/show/?m=mocktour',
    floorPlanImage: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
    pdfBrochureUrl: 'https://example.com/brochure-2001.pdf',
    nearbySchools: 'Rockridge Secondary School, West Bay Elementary',
    nearbyHospitals: 'Lions Gate Hospital, West Vancouver Medical Centre',
    nearbyPublicTransport: 'TransLink Bus Route 250',
    nearbyShoppingCentres: 'Park Royal Shopping Centre',
    nearbyParks: 'Lighthouse Park, Whytecliff Park'
  },
  {
    property_id: 2002,
    owner_id: 'david',
    title: 'The Beverly Crest Pavilion',
    description: 'An architectural tour de force boasting a massive negative-edge pool, private security perimeter, custom wellness wing with steam room and cold plunge, and smart automation system. Exquisite custom cabinetry, travertine stone surfaces, and soaring 14-foot ceilings that frame the city of angels perfectly.',
    price: 35000,
    bedrooms: 5,
    bathrooms: 6,
    area: 8200,
    propertyType: 'Villa',
    amenities: ['Swimming Pool', 'Gym', 'Garden', 'Balcony', 'Terrace', 'Security', 'CCTV', 'Air Conditioning', 'Central Heating', 'Fireplace', 'Laundry Room', 'Storage Room', 'High-Speed Internet', 'Smart Home', 'EV Charging', 'Wheelchair Accessible', 'Pet Friendly', 'Children\'s Play Area', 'Rooftop', 'City View'],
    address: '9514 Sunset Boulevard',
    city: 'Los Angeles',
    province: 'California',
    postalCode: '90210',
    images: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'Available',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Rent',
    currency: 'USD',
    shortDescription: 'Ultra-luxury modern villa with 360-degree canyon and city views in Beverly Crest.',
    country: 'USA',
    areaCommunity: 'Beverly Hills',
    googleMapLocation: 'https://maps.google.com/?q=34.0736,-118.4004',
    nearbyLandmarksText: 'Rodeo Drive, Sunset Strip, Will Rogers Memorial Park',
    kitchens: 2,
    livingRooms: 3,
    diningRooms: 2,
    parkingSpaces: 4,
    floorNumber: 1,
    totalFloors: 2,
    propertySize: 8200,
    lotSize: 22000,
    yearBuilt: 2023,
    propertyCondition: 'New',
    furnishedStatus: 'Furnished',
    monthlyRent: 35000,
    weeklyRent: 8750,
    yearlyRent: 420000,
    securityDeposit: 70000,
    leaseDuration: '12 - 36 Months',
    availableFrom: '2026-07-15',
    coverImage: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80',
    videoTour: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    virtualTour360: 'https://my.matterport.com/show/?m=mocktour',
    floorPlanImage: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
    nearbySchools: 'Beverly Hills High School, Hawthorne Elementary',
    nearbyHospitals: 'Cedars-Sinai Medical Center, UCLA Health Beverly Hills',
    nearbyPublicTransport: 'Metro Local Route 2',
    nearbyShoppingCentres: 'Rodeo Drive, Westfield Century City',
    nearbyParks: 'Will Rogers Memorial Park, Coldwater Canyon Park'
  },
  {
    property_id: 2003,
    owner_id: 'sarah',
    title: 'The Lumina Sky Mansion',
    description: 'A curated high-rise residence featuring custom imported Italian marble, private plunge pool on a double-depth cantilevered terrace, integrated high-speed fiber connectivity, and smart home systems. Floor-to-ceiling glass panels dissolve limits to frame stunning Arabian Gulf sunsets.',
    price: 3400000,
    bedrooms: 3,
    bathrooms: 3.5,
    area: 3400,
    propertyType: 'Condo',
    amenities: ['Swimming Pool', 'Gym', 'Balcony', 'Terrace', 'Elevator', 'Security', 'CCTV', 'Air Conditioning', 'High-Speed Internet', 'Smart Home', 'Pet Friendly', 'Children\'s Play Area', 'Concierge', 'Sea View'],
    address: 'Lumina Tower, Level 44, Marina Promenade',
    city: 'Dubai',
    province: 'Dubai',
    postalCode: '00000',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'Available',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Buy',
    currency: 'AED',
    shortDescription: 'Spectacular half-floor penthouse looking over Palm Jumeirah and the Marina.',
    country: 'UAE',
    areaCommunity: 'Dubai Marina',
    googleMapLocation: 'https://maps.google.com/?q=25.0805,55.1403',
    nearbyLandmarksText: 'Dubai Marina Mall, Marina Promenade, JBR Beach',
    kitchens: 1,
    livingRooms: 1,
    diningRooms: 1,
    parkingSpaces: 2,
    floorNumber: 44,
    totalFloors: 50,
    propertySize: 3400,
    lotSize: 0,
    yearBuilt: 2025,
    propertyCondition: 'New',
    furnishedStatus: 'Furnished',
    estMonthlyRentalIncome: 18000,
    estAnnualRentalIncome: 216000,
    grossRentalYield: 6.35,
    estRoi: 9.8,
    propertyTax: 0,
    hoaMaintenanceFee: 12000,
    estMonthlyMaintenance: 1000,
    coverImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    videoTour: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    virtualTour360: 'https://my.matterport.com/show/?m=mocktour',
    floorPlanImage: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
    nearbySchools: 'Emirates International School, Dubai British School',
    nearbyHospitals: 'King\'s College Hospital, Saudi German Hospital',
    nearbyPublicTransport: 'Dubai Tram (Marina Towers), Dubai Metro (Sobha Realty)',
    nearbyShoppingCentres: 'Dubai Marina Mall, Mall of the Emirates',
    nearbyParks: 'Marina Beach Park, JLT Park'
  },
  {
    property_id: 2004,
    owner_id: 'julian',
    title: 'The Belgravia Regency Duplex',
    description: 'A premium Grade-II listed historic brick façade completely re-engineered on the interior. Features a beautifully curated private courtyard, solid smoked English oak parquet floors, bespoke hand-carved stone fireplaces, and high-efficiency modern structural climate envelopes.',
    price: 12000,
    bedrooms: 3,
    bathrooms: 3,
    area: 2850,
    propertyType: 'Apartment',
    amenities: ['Garden', 'Terrace', 'Security', 'CCTV', 'Air Conditioning', 'Central Heating', 'Fireplace', 'Laundry Room', 'Storage Room', 'High-Speed Internet', 'Concierge', 'City View'],
    address: '14 Eaton Mews South',
    city: 'London',
    province: 'Greater London',
    postalCode: 'SW1W 9PD',
    images: [
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'Available',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Rent',
    currency: 'GBP',
    shortDescription: 'Exquisite two-story duplex residence with private landscaped courtyard in Belgravia.',
    country: 'UK',
    areaCommunity: 'Belgravia',
    googleMapLocation: 'https://maps.google.com/?q=51.4984,-0.1517',
    nearbyLandmarksText: 'Harrods, Hyde Park Corner, Belgrave Square Garden',
    kitchens: 1,
    livingRooms: 2,
    diningRooms: 1,
    parkingSpaces: 1,
    floorNumber: 1,
    totalFloors: 3,
    propertySize: 2850,
    lotSize: 1500,
    yearBuilt: 1910,
    propertyCondition: 'Resale',
    furnishedStatus: 'Furnished',
    monthlyRent: 12000,
    weeklyRent: 3000,
    yearlyRent: 144000,
    securityDeposit: 24000,
    leaseDuration: '12 - 24 Months',
    availableFrom: '2026-08-01',
    coverImage: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
    videoTour: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    virtualTour360: 'https://my.matterport.com/show/?m=mocktour',
    floorPlanImage: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
    nearbySchools: 'Eaton House Belgravia, Westminster School',
    nearbyHospitals: 'The Chelsea and Westminster Hospital, St Thomas\' Hospital',
    nearbyPublicTransport: 'Sloane Square Tube Station, Victoria Station',
    nearbyShoppingCentres: 'Harrods, Peter Jones (Sloane Square)',
    nearbyParks: 'Hyde Park, Belgrave Square Garden'
  },
  {
    property_id: 2005,
    owner_id: 'sarah',
    title: 'The King Street Creative Tech Pavilion',
    description: 'Stunning modern commercial headquarters designed for tech firms or financial boutique advisory groups. Features sandblasted double-brick walls, exposed premium century wood beams, glass-enclosed executive boardrooms, high-efficiency dedicated smart climate control, rooftop amenity lounge, and high-load power backup grids.',
    price: 4200000,
    bedrooms: 0,
    bathrooms: 4,
    area: 6400,
    propertyType: 'Office',
    amenities: ['Elevator', 'Security', 'CCTV', 'Air Conditioning', 'Central Heating', 'Storage Room', 'High-Speed Internet', 'Smart Home', 'EV Charging', 'Wheelchair Accessible', 'Rooftop', 'City View'],
    address: '450 King Street West',
    city: 'Toronto',
    province: 'Ontario',
    postalCode: 'M5V 1K4',
    images: [
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'Available',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Buy',
    currency: 'CAD',
    shortDescription: 'Spectacular boutique double-brick & beam commercial office building in King West.',
    country: 'Canada',
    areaCommunity: 'King West',
    googleMapLocation: 'https://maps.google.com/?q=43.6445,-79.3985',
    nearbyLandmarksText: 'The Well, CN Tower, Rogers Centre',
    kitchens: 1,
    livingRooms: 0,
    diningRooms: 0,
    parkingSpaces: 6,
    floorNumber: 1,
    totalFloors: 2,
    propertySize: 6400,
    lotSize: 4500,
    yearBuilt: 1920,
    propertyCondition: 'Resale',
    furnishedStatus: 'Unfurnished',
    estMonthlyRentalIncome: 21000,
    estAnnualRentalIncome: 252000,
    grossRentalYield: 6.0,
    estRoi: 9.2,
    propertyTax: 24500,
    hoaMaintenanceFee: 0,
    estMonthlyMaintenance: 1500,
    coverImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
    videoTour: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    virtualTour360: 'https://my.matterport.com/show/?m=mocktour',
    floorPlanImage: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
    nearbySchools: 'The Cathedral School, Oasis Alternative SS',
    nearbyHospitals: 'Toronto General Hospital, Mount Sinai Hospital',
    nearbyPublicTransport: 'King Street Streetcar, St. Andrew Subway',
    nearbyShoppingCentres: 'The Well, Eaton Centre',
    nearbyParks: 'Clarence Square Park, Victoria Memorial Square'
  },
  {
    property_id: 2006,
    owner_id: 'julian',
    title: 'The Palm Jumeirah Signature Villa',
    description: 'A masterfully curated beachfront sanctuary on Frond M, offering double-height custom floor plates, infinity pool extending onto private sandy beach, fully-loaded custom show kitchen, luxury glass lifts, and independent staff quarters.',
    price: 55000,
    bedrooms: 6,
    bathrooms: 7,
    area: 9500,
    propertyType: 'Villa',
    amenities: ['Swimming Pool', 'Gym', 'Garden', 'Balcony', 'Terrace', 'Elevator', 'Security', 'CCTV', 'Air Conditioning', 'High-Speed Internet', 'Smart Home', 'EV Charging', 'Pet Friendly', 'Children\'s Play Area', 'Concierge', 'Sea View'],
    address: 'Frond M, Villa 18, Palm Jumeirah',
    city: 'Dubai',
    province: 'Dubai',
    postalCode: '00000',
    images: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'Available',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Rent',
    currency: 'AED',
    shortDescription: 'Spectacular ultra-high-end waterfront beach villa with private beach gate.',
    country: 'UAE',
    areaCommunity: 'Palm Jumeirah',
    googleMapLocation: 'https://maps.google.com/?q=25.1124,55.1328',
    nearbyLandmarksText: 'Nakheel Mall, The Pointe, Palm West Beach',
    kitchens: 2,
    livingRooms: 3,
    diningRooms: 2,
    parkingSpaces: 4,
    floorNumber: 1,
    totalFloors: 2,
    propertySize: 9500,
    lotSize: 14000,
    yearBuilt: 2024,
    propertyCondition: 'New',
    furnishedStatus: 'Furnished',
    monthlyRent: 55000,
    weeklyRent: 13750,
    yearlyRent: 660000,
    securityDeposit: 110000,
    leaseDuration: '12 - 24 Months',
    availableFrom: 'Immediate',
    coverImage: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
    videoTour: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    virtualTour360: 'https://my.matterport.com/show/?m=mocktour',
    floorPlanImage: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
    nearbySchools: 'iCademy Middle East, Regent International School',
    nearbyHospitals: 'Al Zahra Hospital, King\'s College Hospital Marina',
    nearbyPublicTransport: 'Palm Monorail (Nakheel Mall)',
    nearbyShoppingCentres: 'Nakheel Mall, The Pointe',
    nearbyParks: 'Al Ittihad Park, Palm West Beach'
  },
  {
    property_id: 2007,
    owner_id: 'julian',
    title: 'The Coral Gables Oasis Estate',
    description: 'An elegant custom-built Spanish-modern estate situated in prestigious Coral Gables. Designed for refined modern living, this property offers double-height ceilings, a professional chef kitchen with Sub-Zero and Wolf appliances, premium wide-plank French white oak floors, and a private courtyard with a heated saltwater pool.',
    price: 3200000,
    bedrooms: 5,
    bathrooms: 5.5,
    area: 5200,
    propertyType: 'Villa',
    amenities: ['Swimming Pool', 'Gym', 'Garden', 'Balcony', 'Terrace', 'Security', 'CCTV', 'Air Conditioning', 'Central Heating', 'Fireplace', 'Laundry Room', 'Storage Room', 'High-Speed Internet', 'Smart Home', 'EV Charging', 'Pet Friendly'],
    address: '1428 Anastasia Avenue',
    city: 'Miami',
    province: 'Florida',
    postalCode: '33134',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'Available',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Buy',
    currency: 'USD',
    shortDescription: 'Modern Coral Gables luxury estate featuring custom saltwater pool and private gardens.',
    country: 'USA',
    areaCommunity: 'Coral Gables',
    googleMapLocation: 'https://maps.google.com/?q=25.7289,-80.2704',
    nearbyLandmarksText: 'Biltmore Golf Course, Venetian Pool, Miracle Mile',
    kitchens: 2,
    livingRooms: 2,
    diningRooms: 1,
    parkingSpaces: 3,
    floorNumber: 1,
    totalFloors: 2,
    propertySize: 5200,
    lotSize: 15000,
    yearBuilt: 2023,
    propertyCondition: 'New',
    furnishedStatus: 'Furnished',
    estMonthlyRentalIncome: 14000,
    estAnnualRentalIncome: 168000,
    grossRentalYield: 5.25,
    estRoi: 8.8,
    propertyTax: 12500,
    hoaMaintenanceFee: 350,
    estMonthlyMaintenance: 600,
    coverImage: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
    videoTour: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    virtualTour360: 'https://my.matterport.com/show/?m=mocktour',
    floorPlanImage: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
    nearbySchools: 'Coral Gables Senior High, Sunset Elementary School',
    nearbyHospitals: 'Coral Gables Hospital, Doctors Hospital',
    nearbyPublicTransport: 'Coral Gables Trolley, Metrorail (Douglas Road)',
    nearbyShoppingCentres: 'Shops at Merrick Park, Miracle Mile',
    nearbyParks: 'Coral Gables Youth Center, Salvadore Park'
  },
  {
    property_id: 2008,
    owner_id: 'sarah',
    title: 'The Yorkville Glass Sky Residence',
    description: 'Elevate your urban lifestyle in this majestic high-floor corner residence at the premium Yorkville Private Estates. Featuring spectacular unobstructed 270-degree skyline views, ultra-high-end custom Downsview kitchen cabinetry, integrated Miele appliances, and premium automated Crestron light and window shade systems.',
    price: 6500,
    bedrooms: 2,
    bathrooms: 2.5,
    area: 1850,
    propertyType: 'Condo',
    amenities: ['Swimming Pool', 'Gym', 'Balcony', 'Elevator', 'Security', 'CCTV', 'Air Conditioning', 'Central Heating', 'High-Speed Internet', 'Smart Home', 'Pet Friendly', 'Concierge', 'City View'],
    address: '155 Cumberland Street, Level 38',
    city: 'Toronto',
    province: 'Ontario',
    postalCode: 'M5R 1A2',
    images: [
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'Available',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Rent',
    currency: 'CAD',
    shortDescription: 'Magnificent Yorkville sky estate with breathtaking 270-degree Toronto views.',
    country: 'Canada',
    areaCommunity: 'Yorkville Luxury District',
    googleMapLocation: 'https://maps.google.com/?q=43.6702,-79.3932',
    nearbyLandmarksText: 'Royal Ontario Museum, Queen\'s Park, University of Toronto',
    kitchens: 1,
    livingRooms: 1,
    diningRooms: 1,
    parkingSpaces: 2,
    floorNumber: 38,
    totalFloors: 45,
    propertySize: 1850,
    lotSize: 0,
    yearBuilt: 2022,
    propertyCondition: 'New',
    furnishedStatus: 'Furnished',
    monthlyRent: 6500,
    weeklyRent: 1625,
    yearlyRent: 78000,
    securityDeposit: 13000,
    leaseDuration: '12 - 24 Months',
    availableFrom: '2026-07-01',
    coverImage: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    videoTour: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    virtualTour360: 'https://my.matterport.com/show/?m=mocktour',
    floorPlanImage: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
    nearbySchools: 'University of Toronto Schools, Jesse Ketchum Public School',
    nearbyHospitals: 'Mount Sinai Hospital, Toronto General Hospital',
    nearbyPublicTransport: 'Bay & Bloor-Yonge Subway Stations',
    nearbyShoppingCentres: 'Holt Renfrew Centre, Manulife Centre',
    nearbyParks: 'Village of Yorkville Park, Queen\'s Park'
  },
  {
    property_id: 2009,
    owner_id: 'david',
    title: 'The Chelsea Georgian Mews',
    description: 'An exceptional four-story Georgian townhouse nestled in a quiet mews street in Chelsea. Fully restored and modernised with premium architectural finishes, including a light-filled modern steel glass conservatory extension, structural concrete basement spa wing, and hand-fitted bespoke millwork throughout.',
    price: 4950000,
    bedrooms: 4,
    bathrooms: 4,
    area: 3600,
    propertyType: 'Townhouse',
    amenities: ['Gym', 'Garden', 'Balcony', 'Terrace', 'Security', 'CCTV', 'Air Conditioning', 'Central Heating', 'Fireplace', 'Laundry Room', 'Storage Room', 'High-Speed Internet', 'Smart Home', 'Rooftop', 'City View'],
    address: '8 Redburn Street',
    city: 'London',
    province: 'Greater London',
    postalCode: 'SW3 4BX',
    images: [
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'Available',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Buy',
    currency: 'GBP',
    shortDescription: 'Spectacular fully restored Chelsea Georgian townhouse with premium conservatory.',
    country: 'UK',
    areaCommunity: 'Chelsea',
    googleMapLocation: 'https://maps.google.com/?q=51.4872,-0.1651',
    nearbyLandmarksText: 'King\'s Road, Saatchi Gallery, Royal Hospital Chelsea',
    kitchens: 1,
    livingRooms: 2,
    diningRooms: 1,
    parkingSpaces: 1,
    floorNumber: 1,
    totalFloors: 4,
    propertySize: 3600,
    lotSize: 1800,
    yearBuilt: 1890,
    propertyCondition: 'Resale',
    furnishedStatus: 'Semi-Furnished',
    estMonthlyRentalIncome: 15000,
    estAnnualRentalIncome: 180000,
    grossRentalYield: 3.64,
    estRoi: 7.9,
    propertyTax: 8500,
    hoaMaintenanceFee: 0,
    estMonthlyMaintenance: 800,
    coverImage: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
    videoTour: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    virtualTour360: 'https://my.matterport.com/show/?m=mocktour',
    floorPlanImage: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
    nearbySchools: 'Garden House School, Marlborough Primary School',
    nearbyHospitals: 'Royal Brompton Hospital, Chelsea and Westminster Hospital',
    nearbyPublicTransport: 'Sloane Square Subway Station, South Kensington Tube',
    nearbyShoppingCentres: 'King\'s Road Luxury Boutiques, Harrods',
    nearbyParks: 'Ranelagh Gardens, Battersea Park'
  },
  {
    property_id: 2010,
    owner_id: 'sarah',
    title: 'The Design District Flagship Retail',
    description: 'A striking architectural storefront located in the heart of the ultra-high-end Miami Design District. Features double-height concrete facades, structural performance floor-to-ceiling glass vitrines, an open-concept custom floor layout, mezzanine office space, and specialized display lighting systems.',
    price: 18000,
    bedrooms: 0,
    bathrooms: 2,
    area: 2400,
    propertyType: 'Commercial',
    amenities: ['Security', 'CCTV', 'Air Conditioning', 'Central Heating', 'Storage Room', 'High-Speed Internet', 'Smart Home', 'Wheelchair Accessible', 'City View'],
    address: '140 NE 39th Street',
    city: 'Miami',
    province: 'Florida',
    postalCode: '33137',
    images: [
      'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'Available',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Rent',
    currency: 'USD',
    shortDescription: 'Ultra-exclusive double-height flagship retail boutique space in Design District.',
    country: 'USA',
    areaCommunity: 'Miami Design District',
    googleMapLocation: 'https://maps.google.com/?q=25.8124,-80.1918',
    nearbyLandmarksText: 'Institute of Contemporary Art, De la Cruz Collection',
    kitchens: 0,
    livingRooms: 0,
    diningRooms: 0,
    parkingSpaces: 4,
    floorNumber: 1,
    totalFloors: 2,
    propertySize: 2400,
    lotSize: 0,
    yearBuilt: 2021,
    propertyCondition: 'New',
    furnishedStatus: 'Unfurnished',
    monthlyRent: 18000,
    weeklyRent: 4500,
    yearlyRent: 216000,
    securityDeposit: 36000,
    leaseDuration: '36 - 60 Months',
    availableFrom: '2026-09-01',
    coverImage: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80',
    videoTour: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    virtualTour360: 'https://my.matterport.com/show/?m=mocktour',
    floorPlanImage: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
    nearbySchools: 'Design & Architecture Senior High (DASH)',
    nearbyHospitals: 'Mercy Hospital, Jackson Memorial Hospital',
    nearbyPublicTransport: 'Miami Metrobus Route 9, Metromover (School Board)',
    nearbyShoppingCentres: 'Miami Design District, Shops at Midtown Miami',
    nearbyParks: 'Albert Pallot Park, Margaret Pace Park'
  },
  {
    property_id: 1500,
    owner_id: 'david',
    title: 'The Cascades Neopolis',
    description: 'The Cascades Neopolis is a world-class luxury residential project located in the Neopolis Layout, Hyderabad. Designed in collaboration with international consultants – UHA (London) for architecture, Coopers Hill (Singapore) for landscape, and Studio HBA (Singapore) for interiors. Spanning over 7.34 acres with five stunning 63-storey towers, redefine Hyderabad’s skyline with WELL v2 Platinum pre-certified wellness and a high-end global concierge by Quintessentially UK.',
    price: 44800000,
    bedrooms: 4,
    bathrooms: 4.5,
    area: 4150,
    propertyType: 'Apartment',
    amenities: [
      'Amphitheater', 'Cricket Pitch', 'Sauna Bath', 'Tennis Court', 'Spa Luxury Pavilion',
      'Swimming Pool & Cabanas', 'Open Gym', 'Water Conservation, Rainwater Harvesting', 'Mini Theatre'
    ],
    address: 'Neopolis, Kokapet, West Hyderabad',
    city: 'Hyderabad',
    province: 'Telangana',
    postalCode: '500075',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'Active',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Buy',
    monthlyRentEstimate: 194000,
    highlights: [
      'International Design Excellence: Concept Architect UHA London, Landscape Coopers Hill Singapore, Interiors Studio HBA Singapore.',
      'Luxury Concierge by Quintessentially UK: World-class residentes lifestyle desk.',
      'World’s Largest WELL Pre-Certified Residence: Earned WELL v2 Platinum Pre-Certification for premium healthy living standards.',
      'IGBC Platinum Pre-Certified Green Building: Carbon conscious materials and maximum efficiency.',
      'Smart Home Automation: Advanced control across all suites.'
    ],
    builderName: 'GHR Lakshmi Urban Blocks Infra LLP',
    builderDescription: 'GHR Lakshmi Urban Blocks Infra LLP is a leading real estate joint syndicate focused on sustainable, high-rise, wellness-centric master planned spaces incorporating global consultant structures.',
    reraId: 'P02400009538',
    possessionDate: 'Mar, 2030',
    projectSize: '5 Buildings - 1189 units',
    projectAreaCount: '7.34 Acres',
    bhkConfig: '3.5, 4, 4.5 BHK Apartments',
    avgPricePerSft: '₹11.5 K/sq.ft',
    landmarks: {
      school: 'Phoenix Greens School of Learning (CBSE / Cambridge School)',
      metro: 'Raidurg Metro Station',
      hospital: 'Continental Hospitals',
      mall: 'Reliance Smart Point',
      restaurant: 'Cafe Sandwicho'
    }
  },
  {
    property_id: 1501,
    owner_id: 'sarah',
    title: 'Aakriti Miro Skyhomes',
    description: 'A structural masterpiece defining high-efficiency modern luxury in Gachibowli area. Miro homes boast of smart daylight tracking layouts, heavy thermal cladding, and spacious private balcony gardens.',
    price: 18500000,
    bedrooms: 3,
    bathrooms: 3,
    area: 2600,
    propertyType: 'Apartment',
    amenities: ['Terrace Clubroom', 'Fully Equipped Gym', 'EV Charging Bays', 'Billiards Room', 'Central Softwater'],
    address: 'Puppalaguda, near Gachibowli',
    city: 'Hyderabad',
    province: 'Telangana',
    postalCode: '500032',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'Active',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Buy',
    monthlyRentEstimate: 55000,
    highlights: [
      'Seismic resistant structural build design',
      'Centralized rainwater harvesting models',
      'Over 60% open landscaping coverage'
    ],
    builderName: 'Aakriti Infra Structures',
    builderDescription: 'Pioneering structural developers focused on compact eco-luxury residences in West Hyderabad.',
    reraId: 'P02400003194',
    possessionDate: 'Dec, 2027',
    projectSize: '3 Towers - 540 units',
    projectAreaCount: '4.2 Acres',
    bhkConfig: '2, 3 BHK Apartments',
    avgPricePerSft: '₹7.1 K/sq.ft',
    landmarks: {
      school: 'Oakridge International School',
      metro: 'Raidurg Metro Station',
      hospital: 'AIG Hospitals',
      mall: 'Inorbit Mall',
      restaurant: 'Sheraton Feast Desk'
    }
  },
  {
    property_id: 1502,
    owner_id: 'julian',
    title: 'My Home Avatar Peak',
    description: 'Elevated lifestyle towers in Nanakramguda with sweeping views of the Financial District. Promising exceptional structural finish, integrated sports facilities, and direct proximity to corporate hubs.',
    price: 29500000,
    bedrooms: 3,
    bathrooms: 3.5,
    area: 3120,
    propertyType: 'Apartment',
    amenities: ['Grand Sports Arena', 'Central Sky Pavilion Link', 'Skating Rink', 'Yoga Deck', 'Advanced Safety Port'],
    address: 'Gachibowli Financial District Ext',
    city: 'Hyderabad',
    province: 'Telangana',
    postalCode: '500008',
    images: [
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'Active',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Buy',
    monthlyRentEstimate: 85000,
    highlights: [
      'Premium sports lounge and double badminton courts',
      'Rooftop master clubhouse with panoramic pool',
      'Centralized high-capacity fresh air cycling system'
    ],
    builderName: 'My Home Group',
    builderDescription: 'One of the most reputed and trusted real estate builders in South India, celebrated for impeccable timeline execution and structural integrity.',
    reraId: 'P02400001556',
    possessionDate: 'Jun, 2028',
    projectSize: '10 Towers - 2400 units',
    projectAreaCount: '16.5 Acres',
    bhkConfig: '3 BHK Apartments',
    avgPricePerSft: '₹9.4 K/sq.ft',
    landmarks: {
      school: 'Silver Oaks International School',
      metro: 'Nanakramguda Metro Station',
      hospital: 'Care Hospitals',
      mall: 'Reliance Fresh Supermarket',
      restaurant: 'Over The Moon Brew Desk'
    }
  },
  {
    property_id: 1503,
    owner_id: 'david',
    title: 'Rajapushpa Provincia Narsingi',
    description: 'A premium gated community designed to give you a grand resort experience every single day. Featuring expansive green pathways, high acoustic separation walls, and grand architectural aesthetic portals.',
    price: 31500000,
    bedrooms: 3,
    bathrooms: 3.5,
    area: 3450,
    propertyType: 'Apartment',
    amenities: ['Resort Style Lake', 'Squash Court', 'Multi-level Club lounges', 'Premium Mini-theater', 'Daycare Center'],
    address: 'Narsingi, West Hyderabad',
    city: 'Hyderabad',
    province: 'Telangana',
    postalCode: '500075',
    images: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'Active',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Buy',
    monthlyRentEstimate: 95000,
    highlights: [
      'Double-height air-conditioned designer lobbies',
      '100% vehicle-free ground levels for complete safety',
      'Organic composting setup and solar street illuminations'
    ],
    builderName: 'Rajapushpa Properties',
    builderDescription: 'Creating upscale urban landmarks with a deep commitment to timely delivery, quality materials, and meticulous design.',
    reraId: 'P02400002821',
    possessionDate: 'Oct, 2027',
    projectSize: '8 Buildings - 1650 units',
    projectAreaCount: '12.8 Acres',
    bhkConfig: '3, 4 BHK Apartments',
    avgPricePerSft: '₹9.1 K/sq.ft',
    landmarks: {
      school: 'Rockwell International School',
      metro: 'Raidurg Metro Station',
      hospital: 'Star Hospitals Narsingi',
      mall: 'Rajapushpa Boutique Mall',
      restaurant: 'The Glass Onion Dine'
    }
  },
  {
    property_id: 1504,
    owner_id: 'sarah',
    title: 'Aparna One Signature',
    description: 'An elite block of smart-enabled skyscrapers where luxury meets cutting edge. Featuring localized voice controls, automated climate regulation systems, and a professional level indoor bowling alley.',
    price: 72500000,
    bedrooms: 4,
    bathrooms: 5,
    area: 5100,
    propertyType: 'Apartment',
    amenities: ['Voice Automated Concierge', 'Bowling Alley', 'Squash Championship Court', 'Interactive Tech Lounge', 'Cold Plunge Room'],
    address: 'Shard Nagar, Gachibowli',
    city: 'Hyderabad',
    province: 'Telangana',
    postalCode: '500032',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'Active',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Buy',
    monthlyRentEstimate: 210000,
    highlights: [
      'Integrated smart-home server in every unit',
      'Advanced dual-stage water softening plant',
      'Secluded luxury library for residents only'
    ],
    builderName: 'Aparna Constructions',
    builderDescription: 'Pioneers of luxury smart apartments and extensive structural durability, delivering modern excellence in Telangana since 1996.',
    reraId: 'P02400000199',
    possessionDate: 'Immediate Delivery',
    projectSize: '2 Elite Towers - 180 units',
    projectAreaCount: '4.8 Acres',
    bhkConfig: '3, 4 BHK Smart Homes',
    avgPricePerSft: '₹14.2 K/sq.ft',
    landmarks: {
      school: 'Chirec International School',
      metro: 'Hitec City Metro Station',
      hospital: 'Continental Hospitals',
      mall: 'SLN Terminus Mall',
      restaurant: 'Prestige Club Lounge'
    }
  },
  {
    property_id: 1505,
    owner_id: 'julian',
    title: 'Candeur Skyline Tower',
    description: 'A spectacular vertical living development located at the crest of West Hyderabad. This project stands as an iconic design statement, utilizing post-tension floor technology.',
    price: 38500000,
    bedrooms: 4,
    bathrooms: 4,
    area: 3780,
    propertyType: 'Apartment',
    amenities: ['Triple Height Sky Deck', 'Indoor Paddle Court', 'Bespoke Gym', 'Infinity Swimming Loop', 'Kids Digital Library'],
    address: 'Financial District Core',
    city: 'Hyderabad',
    province: 'Telangana',
    postalCode: '500032',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'Active',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Buy',
    monthlyRentEstimate: 110000,
    highlights: [
      'Exquisite panoramic viewing gallery on the 45th level',
      'Advanced triple stage fresh air filtration system',
      'Fully seismic integrated heavy structural base'
    ],
    builderName: 'Candeur Developers',
    builderDescription: 'A dynamic development group redefining state skyline structures with contemporary aesthetics and sturdy high-rise layouts.',
    reraId: 'P02400004948',
    possessionDate: 'Sep, 2029',
    projectSize: '1 Mega Tower - 320 units',
    projectAreaCount: '3.5 Acres',
    bhkConfig: '3.5, 4 BHK Apartments',
    avgPricePerSft: '₹10.1 K/sq.ft',
    landmarks: {
      school: 'Delhi Public School, Gachibowli',
      metro: 'Raidurg Metro Depot',
      hospital: 'Citizen Hospital',
      mall: 'Financial District Plaza',
      restaurant: 'The Westin Gachibowli'
    }
  },
  {
    property_id: 1506,
    owner_id: 'david',
    title: 'Prestige High Fields Gachibowli',
    description: 'Disney-themed high density community providing a delightful atmosphere for growing families. Emphasizing premium active outdoor gardens and high security boundaries.',
    price: 22000000,
    bedrooms: 3,
    bathrooms: 3,
    area: 2840,
    propertyType: 'Apartment',
    amenities: ['Disney Themed Gardens', 'Badminton Court', 'Open Terrace Lounge', 'Aerobics Gym Room', 'Water fountains'],
    address: 'Nanakramguda Financial District',
    city: 'Hyderabad',
    province: 'Telangana',
    postalCode: '500008',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'Active',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Buy',
    monthlyRentEstimate: 62000,
    highlights: [
      'Over 75% wide visual landscaped reserves',
      'Professional level multi-purpose sports pavilion',
      'Zero traffic security perimeter on kids walks'
    ],
    builderName: 'Prestige Estates Projects',
    builderDescription: 'A national real estate stalwart renowned for masterfully developed integrated townships across India, bringing impeccable class.',
    reraId: 'P02400000032',
    possessionDate: 'Ready to Move',
    projectSize: '10 Buildings - 2240 units',
    projectAreaCount: '21.8 Acres',
    bhkConfig: '2.5, 3, 4 BHK Apartments',
    avgPricePerSft: '₹7.7 K/sq.ft',
    landmarks: {
      school: 'Keystone International School',
      metro: 'Hitec City Business District',
      hospital: 'Care Hospitals Gachibowli',
      mall: 'Prestige Business Hub',
      restaurant: 'Jonathan’s Kitchen'
    }
  },
  {
    property_id: 1507,
    owner_id: 'sarah',
    title: 'Phoenix Golf Edge Residences',
    description: 'An architectural paradise looking directly into the lush fairways of the professional Boulder Hills Golf course. Enjoy high ceilings, gourmet designer pantries, and an incredible visual outlook.',
    price: 41000000,
    bedrooms: 4,
    bathrooms: 4.5,
    area: 3600,
    propertyType: 'Apartment',
    amenities: ['Direct Golf Course View', 'Skypool on 30th floor', 'Fully furnished units', 'Luxury Billiard hall', 'Central Steam bath'],
    address: 'Nanakramguda Financial Hub',
    city: 'Hyderabad',
    province: 'Telangana',
    postalCode: '500032',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'Active',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Buy',
    monthlyRentEstimate: 125000,
    highlights: [
      'Double master suites with absolute floor to ceiling glass pane',
      '30th level custom residents sky lounge and pool',
      'Complete home automated remote security and audio controls'
    ],
    builderName: 'Phoenix Group',
    builderDescription: 'Setting state benchmarks for premium office technology parks and ultra high-end luxury residential projects for global executives.',
    reraId: 'P02400001150',
    possessionDate: 'Ready to Move',
    projectSize: '2 Tall Towers - 360 units',
    projectAreaCount: '5.2 Acres',
    bhkConfig: '3, 4 BHK Premium Condos',
    avgPricePerSft: '₹11.3 K/sq.ft',
    landmarks: {
      school: 'The Oakridge School, Gachibowli',
      metro: 'Gachibowli Ring Road Depot',
      hospital: 'Continental Hospitals',
      mall: 'Financial Hub Galleria',
      restaurant: 'The Golf Club Lounge'
    }
  },
  {
    property_id: 1508,
    owner_id: 'julian',
    title: 'GHR Callisto Gachibowli',
    description: 'Premium environment-conscious residences designed with a focus on human energy levels. Featuring personalized study pods, beautiful active sensory pathways, and premium water processing yards.',
    price: 16500000,
    bedrooms: 3,
    bathrooms: 3,
    area: 2450,
    propertyType: 'Apartment',
    amenities: ['Co-Working Study Pods', 'Sensory Reflexology Track', 'Tennis & Basketball Court', 'Vapor Room', 'Rain Harvesting Hub'],
    address: 'Nallagandla near Gachibowli',
    city: 'Hyderabad',
    province: 'Telangana',
    postalCode: '500019',
    images: [
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'Active',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Buy',
    monthlyRentEstimate: 48000,
    highlights: [
      'Clubhouse integrated high speed co-working bays',
      'Active water purification system and continuous power lines',
      'Sensory landscaped reflexology pathway borders'
    ],
    builderName: 'GHR Infra Blocks LLP',
    builderDescription: 'Innovators of health-conscious luxury living spaces, introducing smart human vitals design into modern high-density models.',
    reraId: 'P02400005511',
    possessionDate: 'May, 2028',
    projectSize: '4 Towers - 720 units',
    projectAreaCount: '6.1 Acres',
    bhkConfig: '2.5, 3 BHK Luxury Apartments',
    avgPricePerSft: '₹6.7 K/sq.ft',
    landmarks: {
      school: 'Delhi Public School, Kokapet',
      metro: 'Raidurg Metro Line',
      hospital: 'Continental Hospital',
      mall: 'Citizen Plaza Kokapet',
      restaurant: 'Cafe Callisto'
    }
  },
  {
    property_id: 1509,
    owner_id: 'sarah',
    title: 'The Auroville Sanctum',
    description: 'Auroville Sanctum sets a new horizon for luxury wellness living, styled with Zen-inspired layouts and a natural central lake. Each home boasts massive corner-to-corner visual sky frames and localized thermodynamic air systems.',
    price: 38900000,
    bedrooms: 4,
    bathrooms: 4,
    area: 3680,
    propertyType: 'Apartment',
    amenities: ['Zen Gardens & Tea Pavilion', 'Natural Jogging Lake', 'Acoustic Co-working Pods', 'Heated Indoor Lap Pool', 'Sub-Station Power Net'],
    address: 'Kokapet Elite Layout',
    city: 'Hyderabad',
    province: 'Telangana',
    postalCode: '500075',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'Active',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Buy',
    monthlyRentEstimate: 115000,
    highlights: [
      'Zen-themed master architecture by Tokyo-inspired design hubs',
      'Over 80% natural vegetation and private walking lake',
      'Low thermal conductance design with full solar grid backup'
    ],
    builderName: 'Auroville Infrastructure Group',
    builderDescription: 'Creating niche wellness-oriented communities focusing on low-energy, highly sustainable private estates across South India.',
    reraId: 'P02400006711',
    possessionDate: 'Jun, 2029',
    projectSize: '3 Towers - 480 units',
    projectAreaCount: '5.8 Acres',
    bhkConfig: '3, 4 BHK Luxury Suites',
    avgPricePerSft: '₹10.5 K/sq.ft',
    landmarks: {
      school: 'Phoenix Greens School of Learning',
      metro: 'Raidurg Metro Station',
      hospital: 'Continental Hospitals',
      mall: 'Inorbit Mall West',
      restaurant: 'The Sanctuary Bistro'
    }
  },
  {
    property_id: 1510,
    owner_id: 'julian',
    title: 'Vasavi Crown Heights',
    description: 'An elite benchmark of soaring premium residential skyscrapers positioned at the apex of Kokapet. Configured for high visual density of natural daylight, featuring high structural concrete performance and customized sky deck configurations.',
    price: 49800000,
    bedrooms: 4,
    bathrooms: 4.5,
    area: 4420,
    propertyType: 'Apartment',
    amenities: ['Panoramic Sky Deck Lounge', 'Olympic Swimming Pool', 'Advanced Fitness Center', 'High Speed Smart Lifts', '24/7 Security Command Room'],
    address: 'Kokapet Golden Mile Road',
    city: 'Hyderabad',
    province: 'Telangana',
    postalCode: '500075',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80'
    ],
    status: 'Active',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Buy',
    monthlyRentEstimate: 155000,
    highlights: [
      'Unobstructed Golden Mile layout views',
      'State-of-the-art home threat defense & access systems',
      'Double width balconies for open elevated social spaces'
    ],
    builderName: 'Vasavi Group Builders',
    builderDescription: 'One of Hyderabad’s signature infrastructure giants, crafting towering residential high-rises with premier amenity blocks for three decades.',
    reraId: 'P02400008432',
    possessionDate: 'Dec, 2029',
    projectSize: '6 Towers - 980 units',
    projectAreaCount: '9.2 Acres',
    bhkConfig: '3.5, 4, 4.5 BHK Apartments',
    avgPricePerSft: '₹11.2 K/sq.ft',
    landmarks: {
      school: 'Chirec Academy Kokapet',
      metro: 'Kokapet Ring Road Metro Station',
      hospital: 'Continental Landmark Hospital',
      mall: 'Kokapet Sovereign Plaza',
      restaurant: 'The Crown Pavilion'
    }
  },
  {
    property_id: 1284,
    owner_id: 'david',
    title: 'The Obsidian Pavilion',
    description: 'A structural marvel in concrete, steel, and low-iron architectural glass. Suspended perfectly over the rugged cliffs of West Vancouver, offering panoramic views of the Pacific Ocean. Features a heated 25-meter black-granite infinity lap pool, climate-controlled art gallery foyer, triple-glazed acoustics, and bespoke white-oak paneling throughout.',
    price: 8450000,
    bedrooms: 4,
    bathrooms: 5,
    area: 6200,
    propertyType: 'Estate',
    amenities: ['Oceanfront Overlook', 'Infinity Pool', 'Art Gallery Foyer', 'Custom Wine Room', 'Automated Security Net'],
    address: '2980 Marine Drive',
    city: 'Vancouver',
    province: 'British Columbia',
    postalCode: 'V7V 1M4',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80'
    ],
    openHouseDate: '2026-07-02T13:00:00.000Z',
    status: 'Active',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Buy',
    monthlyRentEstimate: 28000,
    highlights: ['Double-cantilevered structural engineering', 'High-accuracy motorized curtain walls', 'Zero-tolerance raw concrete surfaces', 'Private beach descent trail'],
    builderName: 'West Coast Monolith Corp',
    builderDescription: 'Premium concrete artisans active in the Pacific Northwest since 1994, focusing exclusively on seismic-isolated hillside structures.'
  },
  {
    property_id: 1285,
    owner_id: 'david',
    title: 'Minimalist Canopy Residence',
    description: 'Deep within nature yet featuring industrial lines. This residence balances steel beams with warm Douglas Fir trims. Oversized sliding panels dissolve the barrier between pristine garden landscapes and the interior living lounge.',
    price: 14500,
    bedrooms: 3,
    bathrooms: 3.5,
    area: 4400,
    propertyType: 'Villa',
    amenities: ['Heated Floor slab', 'Passive Solar collection', 'Double Height Lounge', 'Private Forest Trail'],
    address: '442 Cedar Creek Trail',
    city: 'Vancouver',
    province: 'British Columbia',
    postalCode: 'V6R 2K1',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80'
    ],
    openHouseDate: '2026-06-28T14:30:00.000Z',
    status: 'Active',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Rent',
    monthlyRentEstimate: 14500,
    highlights: ['FSC-Certified local Douglas Fir cladding', 'Thermally-insulated structural steel core', 'Smart automated daylight shielding', 'Geothermal groundwater cooling system'],
    builderName: 'Timber & Line Builders',
    builderDescription: 'Award-winning sustainable architectural fabricators specialized in deep forest sensitive structural integrations.'
  },
  {
    property_id: 1286,
    owner_id: 'sarah',
    title: 'The Brutalist Sky Garden',
    description: 'Rising thirty levels above downtown, this penthouse redefines high-density luxury. Double-height exposed concrete pillars anchor a stunning two-level outdoor sky private park with native maple groves.',
    price: 11200000,
    bedrooms: 5,
    bathrooms: 6,
    area: 7800,
    propertyType: 'Penthouse',
    amenities: ['Sky Garden Loft', '24/7 Butler Port', 'Automated Elevator Gate', 'Sauna and Cold Plunge', 'Helipad Access'],
    address: '101 Bay Street Suite 3001',
    city: 'Toronto',
    province: 'Ontario',
    postalCode: 'M5H 2Y2',
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80'
    ],
    openHouseDate: undefined,
    status: 'Active',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Buy',
    monthlyRentEstimate: 42000,
    highlights: ['Aerodynamic high-speed elevator access', 'Independently zoned structural slab system', '360 degree low-iron glass perimeter', 'Fully automated microclimate garden beds'],
    builderName: 'High-Rise Apex Group',
    builderDescription: 'Pioneering structural developers who introduced post-tensioned voided slabs to the Eastern Canadian skies.'
  },
  {
    property_id: 1287,
    owner_id: 'julian',
    title: 'Mid-Century Modernist Restorations',
    description: 'Constructed originally in 1964 by a legendary local master, painstakingly updated. Retains authentic timber ceiling slabs, floor-to-ceiling split modular stone hearths, and original terrazzo grounds.',
    price: 9800,
    bedrooms: 3,
    bathrooms: 2,
    area: 3100,
    propertyType: 'Villa',
    amenities: ['Original Terrazzo', 'Stone Hearth Chimney', 'Eco Cedar shingles', 'Courtyard Garden'],
    address: '883 Rue de la Montagne',
    city: 'Montreal',
    province: 'Quebec',
    postalCode: 'H3G 1Z8',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80'
    ],
    openHouseDate: '2026-07-05T12:00:00.000Z',
    status: 'Active',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Rent',
    monthlyRentEstimate: 9800,
    highlights: ['Painstakingly restored original redwood structural detailing', 'Restored 1964 wet-process terrazzo floors', 'Direct connection with internal atrium courtyard', 'Advanced modern energy envelope integration'],
    builderName: 'Atelier Rose Restorations',
    builderDescription: 'Dedicated to reviving modern architect-designed structures with modern engineering metrics while preserving cultural assets.'
  },
  {
    property_id: 1288,
    owner_id: 'sarah',
    title: 'The Ironwood Townhouse Row',
    description: 'An architectural showcase of vertical wood screening and absolute pure glass facades. Designed to maximize daylight and create private vertical sanctuaries.',
    price: 2450000,
    bedrooms: 2,
    bathrooms: 2.5,
    area: 2200,
    propertyType: 'Townhouse',
    amenities: ['Nordic Oak floors', 'Rooftop Lounge', 'Geothermal Heating System', 'Electric Car Port'],
    address: '12-78 Collier Ave',
    city: 'Toronto',
    province: 'Ontario',
    postalCode: 'M4W 1M1',
    images: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80'
    ],
    openHouseDate: undefined,
    status: 'Active',
    show_on_profile: true,
    show_on_marketplace: true,
    listingIntent: 'Buy',
    monthlyRentEstimate: 7200,
    highlights: ['Integrated vertical solar capture slats', 'Nordic triple-chamber wood frame build', 'Double-height living space looking into a rock garden', 'Permeable active water filtration site design'],
    builderName: 'Metropolitan Urban Form LLC',
    builderDescription: 'Urban dense living strategists focused on reducing ecological footprints while raising acoustic separation benchmarks.'
  }
];

export const INITIAL_INQUIRIES: Inquiry[] = [
  {
    id: 'inq-1',
    property_id: 1284,
    property_title: 'The Obsidian Pavilion',
    realtor_id: 'david',
    name: 'Eleanor Vance',
    email: 'eleanor@vancearchitects.com',
    phone: '+1 (778) 555-8912',
    message: 'We want to schedule a private viewing this Friday. Our portfolio adviser has verified liquid credentials for verification.',
    date: '2026-06-19T14:20:00.000Z'
  },
  {
    id: 'inq-2',
    property_id: 1284,
    property_title: 'The Obsidian Pavilion',
    realtor_id: 'david',
    name: 'René Larson',
    email: 'rlarson@equinoxnord.com',
    phone: '+1 (604) 555-3810',
    message: 'Could you share details on the triple glazing manufacturer? We are looking for high sound dampening due to low proximity to the shoreline wind patterns.',
    date: '2026-06-20T01:10:00.000Z'
  },
  {
    id: 'inq-3',
    property_id: 1286,
    property_title: 'The Brutalist Sky Garden',
    realtor_id: 'sarah',
    name: 'Charles Belmont',
    email: 'c.belmont@belmortholdings.co',
    phone: '+1 (416) 555-1038',
    message: 'Interested in the Heliport coordinates and slot scheduling contract. Please send over condo bylaws.',
    date: '2026-06-18T10:05:00.000Z'
  }
];

export const INITIAL_USERS: User[] = [
  {
    id: 'buyer1',
    name: 'Arthur Pendelton',
    email: 'buyer@getsft.com',
    role: 'buyer',
    savedPropertyIds: [1284, 1287]
  },
  {
    id: 'david',
    name: 'David Vandervelde',
    email: 'david@getsft.com',
    role: 'realtor',
    savedPropertyIds: [],
    realtorProfile: INITIAL_REALTORS[0]
  },
  {
    id: 'sarah',
    name: 'Sarah Sterling',
    email: 'sarah@getsft.com',
    role: 'realtor',
    savedPropertyIds: [],
    realtorProfile: INITIAL_REALTORS[1]
  },
  {
    id: 'julian',
    name: 'Julian Rose',
    email: 'julian@getsft.com',
    role: 'realtor',
    savedPropertyIds: [],
    realtorProfile: INITIAL_REALTORS[2]
  }
];

const LOCAL_STORAGE_KEY = 'getsft_mvp_state';

interface AppState {
  realtors: Realtor[];
  properties: Property[];
  inquiries: Inquiry[];
  users: User[];
  currentUser: User | null;
}

export function loadState(): AppState {
  if (typeof window === 'undefined') {
    return {
      realtors: INITIAL_REALTORS,
      properties: INITIAL_PROPERTIES,
      inquiries: INITIAL_INQUIRIES,
      users: INITIAL_USERS,
      currentUser: null,
    };
  }

  const stored = localStorage.getItem(LOCAL_STORAGE_KEY);
  if (stored) {
    try {
      const parsed = JSON.parse(stored);
      // Ensure essential fields exist
      if (parsed.realtors && parsed.properties && parsed.inquiries && parsed.users) {
        // First self-heal/synchronize all existing properties with initial attributes
        let mergedProperties = parsed.properties.map((p: any) => {
          const matchedInitial = INITIAL_PROPERTIES.find(ip => ip.property_id === p.property_id);
          return {
            ...matchedInitial, // Default to initial structure to ensure modern properties exist
            ...p,
            listingIntent: p.listingIntent || matchedInitial?.listingIntent || (p.price < 100000 ? 'Rent' : 'Buy'),
            show_on_marketplace: p.show_on_marketplace !== undefined ? p.show_on_marketplace : (matchedInitial?.show_on_marketplace !== undefined ? matchedInitial.show_on_marketplace : true),
            show_on_profile: p.show_on_profile !== undefined ? p.show_on_profile : (matchedInitial?.show_on_profile !== undefined ? matchedInitial.show_on_profile : true),
            monthlyRentEstimate: p.monthlyRentEstimate || matchedInitial?.monthlyRentEstimate || Math.round((p.price || 4000000) * 0.0035)
          };
        });

        // Now dynamically append any newly introduced properties from INITIAL_PROPERTIES that do not exist yet in localStorage
        const existingIds = new Set(mergedProperties.map((p: any) => p.property_id));
        const missingFromCache = INITIAL_PROPERTIES.filter(ip => !existingIds.has(ip.property_id));
        if (missingFromCache.length > 0) {
          mergedProperties = [...mergedProperties, ...missingFromCache];
        }

        parsed.properties = mergedProperties;
        
        // Also self-heal realtors listing references & preserve custom realtors (e.g. Siddique)
        const initialRealtorIds = new Set(INITIAL_REALTORS.map(r => r.id));
        const customRealtors = parsed.realtors ? parsed.realtors.filter((pr: any) => pr && !initialRealtorIds.has(pr.id)) : [];
        
        // Scan parsed.users for any realtors with registered profiles not yet in customRealtors
        const userRealtors = parsed.users ? parsed.users
          .filter((u: any) => u && u.role === 'realtor' && u.realtorProfile && !initialRealtorIds.has(u.id))
          .map((u: any) => u.realtorProfile) : [];
        
        const allCustomRealtors = [...customRealtors];
        userRealtors.forEach((ur: any) => {
          if (!allCustomRealtors.some((cr: any) => cr.id === ur.id)) {
            allCustomRealtors.push(ur);
          }
        });
        
        parsed.realtors = [
          ...INITIAL_REALTORS.map(r => {
            const existing = parsed.realtors ? parsed.realtors.find((pr: any) => pr && pr.id === r.id) : null;
            return { ...r, ...existing };
          }),
          ...allCustomRealtors
        ];

        return parsed as AppState;
      }
    } catch (e) {
      console.error('Error loading state from localStorage:', e);
    }
  }

  // Fallback / Initial
  const initialState: AppState = {
    realtors: INITIAL_REALTORS,
    properties: INITIAL_PROPERTIES,
    inquiries: INITIAL_INQUIRIES,
    users: INITIAL_USERS,
    currentUser: null, // Start as clean guest so users can explicitly join or sign in with their Realtor profile!
  };
  saveState(initialState);
  return initialState;
}

export function saveState(state: AppState) {
  if (typeof window !== 'undefined') {
    localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(state));
  }
}
